/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package vendingmachine;

import vendingmachine.mech.Manipulate;

public class App {
    public static void main(String[] args) {
        Manipulate manipulate = new Manipulate();
        manipulate.start();
    }
}
